### ISSUE TITLE
wrong result when downloading event catalogue

### ISSUE THREAD

**Issue by wangliang1989** [crotwell/sod#5]
the xml file is
```
<?xml version="1.0"?>
<sod>
<eventArm>
    <fdsnEvent>
        <host>service.iris.edu</host>
        <originTimeRange>
            <startTime>1999-09-19T00:00:00.000Z</startTime>
            <endTime>2019-09-19T00:00:00.000Z</endTime>
        </originTimeRange>
        <boxArea>
            <latitudeRange>
                <min>21.5</min>
                <max>25.5</max>
            </latitudeRange>
            <longitudeRange>
                <min>119</min>
                <max>122.5</max>
            </longitudeRange>
        </boxArea>
        <magnitudeRange>
            <min>5</min>
            <max>10</max>
        </magnitudeRange>
    </fdsnEvent>
    <printlineEventProcess/>
    <CSVEventPrinter>  <!-- save catalog to csv file -->
        <filename>taiwan_1999-2019.csv</filename>
    </CSVEventPrinter>
</eventArm>
</sod>
```
sod will download events whose magnitude lower than 5

**Comment by wangliang1989** [comment]
```
<?xml version="1.0"?>
<sod>
<eventArm>
    <fdsnEvent>
        <host>service.iris.edu</host>
        <originTimeRange>
            <startTime>1999-09-19T00:00:00.000Z</startTime>
            <endTime>2019-09-19T00:00:00.000Z</endTime>
        </originTimeRange>
        <boxArea>
            <latitudeRange>
                <min>21.5</min>
                <max>25.5</max>
            </latitudeRange>
            <longitudeRange>
                <min>119</min>
                <max>122.5</max>
            </longitudeRange>
        </boxArea>
        <magnitudeRange>
            <min>5</min>
            <max>10</max>
        </magnitudeRange>
    </fdsnEvent>
    <printlineEventProcess/>
    <CSVEventPrinter>  <!-- save catalog to csv file -->
        <filename>taiwan_1999-2019.csv</filename>
    </CSVEventPrinter>
</eventArm>
</sod>
```

**Comment by crotwell** [comment]
Events can have multiple magnitudes and the magnitudeRange criteria merely check to see if the event has a magnitude within the given range, not that all magnitudes associated with an event are within that range. 

If you want that functionality, you may wish to either specify a magnitude type, like <magType>mb</magType>, or have an additional <magnitudeRange> element outside of the <fdsnEvent> that also includes the <largest> and/or <smallest> criteria because <any> is the default.

See 
http://www.seis.sc.edu/sod/ingredients/magnitudeRange.html

**Comment by wangliang1989** [comment]
Thank you for your answering.
I changed this xml to this:
```
<?xml version="1.0"?>
<sod>
<eventArm>
    <fdsnEvent>
        <host>service.iris.edu</host>
        <originTimeRange>
            <startTime>1999-09-19T00:00:00.000Z</startTime>
            <endTime>2019-09-19T00:00:00.000Z</endTime>
        </originTimeRange>
        <boxArea>
            <latitudeRange>
                <min>21.5</min>
                <max>25.5</max>
            </latitudeRange>
            <longitudeRange>
                <min>119</min>
                <max>122.5</max>
            </longitudeRange>
        </boxArea>
        <magnitudeRange>
            <min>6</min>
            <max>10</max>
            <magType>MW</magType>
        </magnitudeRange>
    </fdsnEvent>
    <printlineEventProcess/>
</eventArm>
</sod>
```
I will receive some info like :
```
Taiwan (24.4, 121.8) 33 km 1999/09/20 18:02:22 UTC 4.7 mb
```

**Comment by crotwell** [comment]
You are dealing with several issues here. 

First, the &lt;magnitudeRange> inside of the &lt;fdsnEvent> is sent to the server, which is different from a &lt;magnitudeRange> outside the &lt;fdsnEvent> which SOD applies after the events are received. This can have an effect as I have no control over how the server interprets the query. If you copy the &lt;magnitudeRange> and also put it below the ending &lt;/fdsnEvent> line you will see that 4.7 is not printed. Note you might want to change MW to Mw to allow any events to pass as MW is not a magnitude type at IRIS.

Second, the printed message only prints the preferred magnitude for the preferred origin, which may not be the same one as the server used to match the query. And so seeing "4.7 mb" does not mean that there is not a magnitude associated with the event that is bigger than 6, just that the preferred magnitude is 4.7. This is confusing, but other users may actually want these.

Third, you are forcing SOD to use the IRIS event service instead of the default USGS event service. That is certainly a reasonable choice if you are sure that is what you want. However, be aware that once an event is old enough for it to be in the ISC catalog, that becomes the value IRIS uses. The ISC catalog aims for "having everything" rather than "having the best" and so if you look at the actual results from IRIS for this 4.7 quake, you will see it has several magnitudes, most of which probably should not be used. Here is the URL that will show you what SOD sees:

http://service.iris.edu/fdsnws/event/1/query?includeallmagnitudes=true&magnitudetype=MW&maxlatitude=25.5&maxlongitude=122.5&maxmagnitude=10.0&minlatitude=21.5&minlongitude=119.0&minmagnitude=6.0&orderby=time-asc&starttime=1999-09-20T18:02:00Z&endtime=1999-09-20T18:02:23Z

Note that the event does in fact contain a magnitude with value 6.3, but is not a MW magnitude. Unfortunately the service interprets the request in a confusing way, but SOD can't do much about that. In general, I have found that using the IRIS server, or equivalently the ISC server, can be problematic because of disagreement about the search criteria and because ISC solutions can contain many, many magnitudes and origins that the end user may not really want. That is why the default for SOD is the USGS event service. Removing the <host> tag will switch back to the USGS. Note that the host for the event service can be different from the host for stations and seismograms.

**Comment by crotwell** [comment]
Some more testing, I think that the IRIS event server is actually handling the query incorrectly. I have filed a bug report with them.

**Comment by wangliang1989** [comment]
Thank you for your answering. I lack of understanding about complexity of earthquakes.
